#!/bin/bash
#$ -l rmem=20G -l mem=20G
#$ -pe openmp 8
#$ -j y
#$ -l h_rt=05:00:00
#$ -t 1-300
#$ -m a
#$ -M skariotis1@sheffield.ac.uk
#$ -P rse

module load apps/R/3.4.0/gcc-4.8.5
#module load mpi/openmi/2.1.1/gcc-6.2

#Number of cores
cores=8

# Inputs

# Select genesets file
gs="sok_test_L1000.RDS"

# Select desired relationships based on the table (github)
# Example: rels="1,2,4,6"
rels="7"

# Select whether you want partial-correlation(0) or not(1)
pcor="0"

# Output folder
ofo="output_sok"

# Run code (no need to change that) 

Rscript PCxN_estimates02.R $SGE_TASK_ID $gs $cores $ofo
echo estimates02 done !!!

# Aggregating the 2 matrices
Rscript PCxN_estimates03.R $gs $ofo
echo estimates03 done !!!

echo PCxN Complete !!!
