#!/bin/bash
#$ -l rmem=5G -l mem=5G
#$ -pe openmp 8
#$ -t 1-134
#$ -j y
#$ -l h_rt=5:00:00
#$ -l hostname=!sharc-node126
#$ -m bea
#$ -M kkoler1@sheffield.ac.uk
#$ -P rse

module load apps/R/3.5.1/gcc-4.8.5
#module load mpi/openmi/2.1.1/gcc-6.2

#Number of cores
cores=12

# Inputs

# Select genesets file
gs="MSigDB.L1000CDS2.staticmod.6.subset.RDS"

# Select desired relationships based on the table (github)
# Example: rels="1,2,4,6"
rels="7"

# Select whether you want partial-correlation(0) or not(1)
pcor="0"

# Output folder
ofo="output_MSigDB.L1000CDS.staticmod.6.subset_rel7"

# Run code (no need to change that) 

# Run tissue-matrices generation
Rscript improved_PCxN_estimates00.R $gs
echo estimates00 done !!!
 
Rscript PCxN_estimates01.R $SGE_TASK_ID $cores $rels $gs $pcor $ofo
echo estimates01 done !!!
